version: '2'

volumes:
  settings:

services:
  app:
    build: ./app
    restart: always
    expose:
      - "5000"
    depends_on:
      - browser

  browser:
    image: balenablocks/browser
    privileged: true
    network_mode: host
    volumes:
      - 'settings:/data'

