# syntax=docker/dockerfile:1
FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-python
WORKDIR /app
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
RUN apk add --no-cache gcc musl-dev linux-headers 
RUN pip install flask
EXPOSE 5000
COPY . .
CMD ["python", "-m", "flask", "run"]


